package day_2;

//You are given two strings s and t.
//‌
//String t is generated by random shuffling string s and then add one more letter at a random position.
//‌
//Return the letter that was added to t.
//‌
//Example 1:
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.

import java.util.Scanner;
public class FindExtra {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter the String 1");
		String s = sc.nextLine();
		System.out.println("Enter the String 2");
		String t = sc.nextLine();
		int xor = 0;
        for (char c : s.toCharArray()) xor ^= c;
        for (char c : t.toCharArray()) xor ^= c;
        System.out.println("The extra character is: " + (char)xor);
	}

}
